version: "3.9"
services:
  app:
    build: .
    volumes:
      - ./app:/app
    # env_file: .env
    ports:
      - 3000:3000
    depends_on:
      - db
    links:
      - db
    entrypoint: go run main.go
    restart: always

  db:
    image: mongo:4.4.3
    restart: always
    ports:
      - 27017:27017

volumes:
  bundle: