// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: short_url/short_url.proto

package url_shortener_go

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on CreateShortUrlReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *CreateShortUrlReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateShortUrlReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateShortUrlReqMultiError, or nil if none found.
func (m *CreateShortUrlReq) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateShortUrlReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Url

	if len(errors) > 0 {
		return CreateShortUrlReqMultiError(errors)
	}

	return nil
}

// CreateShortUrlReqMultiError is an error wrapping multiple validation errors
// returned by CreateShortUrlReq.ValidateAll() if the designated constraints
// aren't met.
type CreateShortUrlReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateShortUrlReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateShortUrlReqMultiError) AllErrors() []error { return m }

// CreateShortUrlReqValidationError is the validation error returned by
// CreateShortUrlReq.Validate if the designated constraints aren't met.
type CreateShortUrlReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateShortUrlReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateShortUrlReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateShortUrlReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateShortUrlReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateShortUrlReqValidationError) ErrorName() string {
	return "CreateShortUrlReqValidationError"
}

// Error satisfies the builtin error interface
func (e CreateShortUrlReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateShortUrlReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateShortUrlReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateShortUrlReqValidationError{}

// Validate checks the field values on CreateShortUrlResp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateShortUrlResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateShortUrlResp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateShortUrlRespMultiError, or nil if none found.
func (m *CreateShortUrlResp) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateShortUrlResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ShortUrl

	if len(errors) > 0 {
		return CreateShortUrlRespMultiError(errors)
	}

	return nil
}

// CreateShortUrlRespMultiError is an error wrapping multiple validation errors
// returned by CreateShortUrlResp.ValidateAll() if the designated constraints
// aren't met.
type CreateShortUrlRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateShortUrlRespMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateShortUrlRespMultiError) AllErrors() []error { return m }

// CreateShortUrlRespValidationError is the validation error returned by
// CreateShortUrlResp.Validate if the designated constraints aren't met.
type CreateShortUrlRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateShortUrlRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateShortUrlRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateShortUrlRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateShortUrlRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateShortUrlRespValidationError) ErrorName() string {
	return "CreateShortUrlRespValidationError"
}

// Error satisfies the builtin error interface
func (e CreateShortUrlRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateShortUrlResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateShortUrlRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateShortUrlRespValidationError{}

// Validate checks the field values on RedirectShortUrlReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RedirectShortUrlReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RedirectShortUrlReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RedirectShortUrlReqMultiError, or nil if none found.
func (m *RedirectShortUrlReq) ValidateAll() error {
	return m.validate(true)
}

func (m *RedirectShortUrlReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ShortUrl

	if len(errors) > 0 {
		return RedirectShortUrlReqMultiError(errors)
	}

	return nil
}

// RedirectShortUrlReqMultiError is an error wrapping multiple validation
// errors returned by RedirectShortUrlReq.ValidateAll() if the designated
// constraints aren't met.
type RedirectShortUrlReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RedirectShortUrlReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RedirectShortUrlReqMultiError) AllErrors() []error { return m }

// RedirectShortUrlReqValidationError is the validation error returned by
// RedirectShortUrlReq.Validate if the designated constraints aren't met.
type RedirectShortUrlReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RedirectShortUrlReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RedirectShortUrlReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RedirectShortUrlReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RedirectShortUrlReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RedirectShortUrlReqValidationError) ErrorName() string {
	return "RedirectShortUrlReqValidationError"
}

// Error satisfies the builtin error interface
func (e RedirectShortUrlReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRedirectShortUrlReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RedirectShortUrlReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RedirectShortUrlReqValidationError{}

// Validate checks the field values on RedirectShortUrlResp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RedirectShortUrlResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RedirectShortUrlResp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RedirectShortUrlRespMultiError, or nil if none found.
func (m *RedirectShortUrlResp) ValidateAll() error {
	return m.validate(true)
}

func (m *RedirectShortUrlResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Url

	if len(errors) > 0 {
		return RedirectShortUrlRespMultiError(errors)
	}

	return nil
}

// RedirectShortUrlRespMultiError is an error wrapping multiple validation
// errors returned by RedirectShortUrlResp.ValidateAll() if the designated
// constraints aren't met.
type RedirectShortUrlRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RedirectShortUrlRespMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RedirectShortUrlRespMultiError) AllErrors() []error { return m }

// RedirectShortUrlRespValidationError is the validation error returned by
// RedirectShortUrlResp.Validate if the designated constraints aren't met.
type RedirectShortUrlRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RedirectShortUrlRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RedirectShortUrlRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RedirectShortUrlRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RedirectShortUrlRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RedirectShortUrlRespValidationError) ErrorName() string {
	return "RedirectShortUrlRespValidationError"
}

// Error satisfies the builtin error interface
func (e RedirectShortUrlRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRedirectShortUrlResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RedirectShortUrlRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RedirectShortUrlRespValidationError{}
