// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: short_url/short_url.proto

package url_shortener_go

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UrlShortenerClient is the client API for UrlShortener service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UrlShortenerClient interface {
	CreateShortUrl(ctx context.Context, in *CreateShortUrlReq, opts ...grpc.CallOption) (*CreateShortUrlResp, error)
	RedirectToShortUrl(ctx context.Context, in *RedirectToShortUrlReq, opts ...grpc.CallOption) (*RedirectToShortUrlResp, error)
}

type urlShortenerClient struct {
	cc grpc.ClientConnInterface
}

func NewUrlShortenerClient(cc grpc.ClientConnInterface) UrlShortenerClient {
	return &urlShortenerClient{cc}
}

func (c *urlShortenerClient) CreateShortUrl(ctx context.Context, in *CreateShortUrlReq, opts ...grpc.CallOption) (*CreateShortUrlResp, error) {
	out := new(CreateShortUrlResp)
	err := c.cc.Invoke(ctx, "/short_url.UrlShortener/CreateShortUrl", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *urlShortenerClient) RedirectToShortUrl(ctx context.Context, in *RedirectToShortUrlReq, opts ...grpc.CallOption) (*RedirectToShortUrlResp, error) {
	out := new(RedirectToShortUrlResp)
	err := c.cc.Invoke(ctx, "/short_url.UrlShortener/RedirectToShortUrl", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UrlShortenerServer is the server API for UrlShortener service.
// All implementations must embed UnimplementedUrlShortenerServer
// for forward compatibility
type UrlShortenerServer interface {
	CreateShortUrl(context.Context, *CreateShortUrlReq) (*CreateShortUrlResp, error)
	RedirectToShortUrl(context.Context, *RedirectToShortUrlReq) (*RedirectToShortUrlResp, error)
	mustEmbedUnimplementedUrlShortenerServer()
}

// UnimplementedUrlShortenerServer must be embedded to have forward compatible implementations.
type UnimplementedUrlShortenerServer struct {
}

func (UnimplementedUrlShortenerServer) CreateShortUrl(context.Context, *CreateShortUrlReq) (*CreateShortUrlResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateShortUrl not implemented")
}
func (UnimplementedUrlShortenerServer) RedirectToShortUrl(context.Context, *RedirectToShortUrlReq) (*RedirectToShortUrlResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RedirectToShortUrl not implemented")
}
func (UnimplementedUrlShortenerServer) mustEmbedUnimplementedUrlShortenerServer() {}

// UnsafeUrlShortenerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UrlShortenerServer will
// result in compilation errors.
type UnsafeUrlShortenerServer interface {
	mustEmbedUnimplementedUrlShortenerServer()
}

func RegisterUrlShortenerServer(s grpc.ServiceRegistrar, srv UrlShortenerServer) {
	s.RegisterService(&UrlShortener_ServiceDesc, srv)
}

func _UrlShortener_CreateShortUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateShortUrlReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UrlShortenerServer).CreateShortUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/short_url.UrlShortener/CreateShortUrl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UrlShortenerServer).CreateShortUrl(ctx, req.(*CreateShortUrlReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UrlShortener_RedirectToShortUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RedirectToShortUrlReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UrlShortenerServer).RedirectToShortUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/short_url.UrlShortener/RedirectToShortUrl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UrlShortenerServer).RedirectToShortUrl(ctx, req.(*RedirectToShortUrlReq))
	}
	return interceptor(ctx, in, info, handler)
}

// UrlShortener_ServiceDesc is the grpc.ServiceDesc for UrlShortener service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UrlShortener_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "short_url.UrlShortener",
	HandlerType: (*UrlShortenerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateShortUrl",
			Handler:    _UrlShortener_CreateShortUrl_Handler,
		},
		{
			MethodName: "RedirectToShortUrl",
			Handler:    _UrlShortener_RedirectToShortUrl_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "short_url/short_url.proto",
}
